version: "3.3"
services:
  pg:
    image: snzip/pg-orafce:11
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    restart: always
  redis:
    image: "redis:alpine"
    restart: always
volumes:
  pg-data: